apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: lbg-ns
  labels:
    app: patient-service
spec:
  selector:
    app: patient-service
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: lbg-ns
  labels:
    app: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP
  type: LoadBalancer
